/** @format */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Header from '@/components/header';
import { Footer } from '@/components/footer';
import { ApolloWrapper } from '@/lib/apollo-wrapper';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable,
        )}
      >
        <ApolloWrapper>
          <div className="hidden flex-col md:flex">
            <header>
              <Header />
            </header>
            <main>{children}</main>
            <footer className="min-h-52">
              <Footer />
            </footer>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
}
